# coding=utf-8

DEBUG = True
SECRET_KEY = 'Gzk3NzY4NTYrOTgyMjg0MmUwMDUyY2Nc'

HOME_TITLE = "7video"
FORUMS_PER_PAGE = 10

DATABASE = "/data/7video/7video.db"
SQLALCHEMY_DATABASE_URI = "sqlite:////data/7video/7video.db"
SQLALCHEMY_ECHO = False
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_POOL_RECYCLE = 280
